<template>
  <div class="loader-container">
    <div class="loadingio-spinner-ripple-fhtn6uda41r"><div class="ldio-a1jwjhqtc8">
    <div></div><div></div>
    </div></div>
  </div>
</template>
<script lang="ts">
import { Component, Vue } from 'vue-property-decorator'
@Component
export default class Loader extends Vue {
}
</script>
<style lang="scss" scoped>
  .loader-container{
    position: fixed;
    top: 0;
    left: 0;
    z-index: 9999;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.7);
    display: flex;
    align-items: center;
    justify-content: center;
  }
  @keyframes ldio-a1jwjhqtc8 {
  0% {
    top: 96px;
    left: 96px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 18px;
    left: 18px;
    width: 156px;
    height: 156px;
    opacity: 0;
  }
}.ldio-a1jwjhqtc8 div {
  position: absolute;
  border-width: 4px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-a1jwjhqtc8 1s cubic-bezier(0,0.2,0.8,1) infinite;
}.ldio-a1jwjhqtc8 div:nth-child(1) {
  border-color: #df1317;
  animation-delay: 0s;
}
.ldio-a1jwjhqtc8 div:nth-child(2) {
  border-color: #e4934b;
  animation-delay: -0.5s;
}
.loadingio-spinner-ripple-fhtn6uda41r {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: transparent;
}
.ldio-a1jwjhqtc8 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-a1jwjhqtc8 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
